### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by xiconet**
here we go again

### CODE REVIEW

**Comment by ncw** [comment]
golint is working again which is good so it means the tests really should work this time :crossed_fingers: 

Can you rebase your patch please? You appear to have pulled in 38 commits somehow!

**Comment by xiconet** [comment]
Sorry for this mess. I did rebase my patch, but only after these commits appeared. I'm not quite sure I did it correctly however.
Besides this, the tests are still failing. I don't know why.

**Comment by ncw** [comment]
I've fixed the merge and merged this in 3ba49835f4db01d6329782cbdc7a0a8bb3a26c5f - thank you very much :-)

I made a couple of small tweaks to your commit:
  * move making the regexp out the loop and use regexp.MustCompile
  * check to see if the regexp matched before using its output

**Comment by xiconet** [comment]
Great! Thank you very much.

**Pull request closed without merging**
