### PR TITLE
Update utils.go

### PR DESCRIPTION
**Pull request by xiconet**
Fix the BAD_ATTRIBUTE error which occurs when the decoded `{"n":"name"}` string includes extra characters which are not NUL

### CODE REVIEW

**Comment by xiconet** [comment]
Here is the same PR I did some time ago. 
How would I configure this Travis thing to pass the login test?

**Comment by ncw** [comment]
It looks like the username / password needed to run the integration tests [aren't available for pull requests](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

I've changed the the tests to skip the integration tests if the credentials aren't available.

So if you could rebase your PR on master and push again then hopefully the tests will run clean!

**Comment by xiconet** [comment]
Hum, this time there's a problem seemingly related to https://golang.org/x/lint/golint returning 404 at the moment. At least I'm learning to use git in the meantime. 
Cheers

**Comment by ncw** [comment]
Grrr!  That is https://github.com/golang/lint/issues/397

I've put in a work-around for that in 89895963aecd77a21e049453182288dd01223ed7

If you rebase and re-push then you'll get that fix too!

> At least I'm learning to use git in the meantime.

:-)

Can you rebase your code instead of merging?  So `git fetch` then `git rebase origin/master` in your branch, then you'll have to use the `--force` flag when you `git push` it up.

That is the say it is normally done for pull requests - it makes it much easier for reviewers to look at your code.

Thanks

**Comment by xiconet** [comment]
Ok, I'll try to rebase, thanks for the tip.

**Pull request closed without merging**
