### PR TITLE
Add method to check quota

### PR DESCRIPTION
**Pull request by ptman**

### CODE REVIEW

**Comment by ncw** [comment]
This looks nice.  Are you still interested in having it merged?

It could do with some tests if so.

**Comment by ptman** [comment]
I haven't used go-mega in a couple of years. It seems like travis can't run tests now at all. What did you have in mind?

**Comment by ncw** [comment]
If you were to rebase your pull request, then you'll find the tests will work.

If you could write a test to exercise the API - perhaps that is calling it and sanity checking the output - that would be perfect :-)

**Comment by ncw** [comment]
I have rebased and merged this.  A test would be nice in a future PR, but I'd rather not lose the code - thanks :-)

**Pull request merged**
